### ISSUE TITLE
Improve Tagbar tag UI/UX for removing tags

### ISSUE THREAD

**Issue by Rperry2174** [grafana/pyroscope#1201]
As of right now its kind of difficult to remove tags. I think there are a series of improvements we can make to tags to accomplish two goals:

1. make it easier to remove tags
2. make it easier to take advantage of advanced tag features (like AND or OR queries in FlameQL)

for now, for this issue I will focus on No.1 , but in a way that will leave room for No.2. 

Here is what I'm thinking as a rough image:
<img width="878" alt="image" src="https://user-images.githubusercontent.com/23323466/176911120-731c9609-adba-4a19-9d35-727ebbeb2f33.png">

1. Create a _new_ "pill" component that puts tag values inside a pill (this component will be extended further in #1202)
2. Add a "x" to the side of that pill which allows you to remove that tag value with one click
3. if a tag value is removed and leaves a tag _key_ with no value then the tag key should be removed also
4. From a style standpoint we should start with the one in the image that is inside the tag bar, but also considering some of the others so lets make the css with variables so we can change easily if we want

**Comment by pavelpashkovsky** [comment]
I spent some time investigating how to improve existing tags bar.
About existing solution (what is closed for now):
Initially span with tag has display: inline. Current UI based on setting css prop display: inline-flex/block for tag. Otherwise we can't do correct placement of close button / tag menu. If we set back inline for tag, it will improve situation with unmatching layers, but we can't set correct position of close button and tag menu.
Then I spent some time researching is there any other solutions like this. I found couple of popular libs for highlighting code.
1) CodeMirror https://codemirror.net/
Prometheus developers even created a promql extension for this lib (https://github.com/prometheus/codemirror-promql). But it has been archived. seems like they use CM here https://demo.promlens.com/
2) https://microsoft.github.io/monaco-editor/
https://github.com/prometheus-community/monaco-promql
