### ISSUE TITLE
Make flameql ignore spaces

### ISSUE THREAD

**Issue by eh-am** [grafana/pyroscope#1258]
The query `cart.service.dotnet.cp{d      ="dwad"}` should work independent of the amoutn of spaces.

We could solve that at different levels, but I believe the easiest one is to do it at the flameql parser level.

![image](https://user-images.githubusercontent.com/6951209/178783041-b52a4ea1-c261-4202-a38e-bf3e04158e6a.png)

![image](https://user-images.githubusercontent.com/6951209/178783018-475dfee9-a489-4546-949e-9241774fac5b.png)

**Comment by kolesnikovae** [comment]
Yeah, we definitely should make it work with spaces. As a quick fix I'm thinking about using regex for tag matchers instead of parsing, e.g something like [this](https://go.dev/play/p/wSe9Dr3ibUG): `^\s*(\w*)\s*(=|=~|!=|!~)\s*"(.*)"\s*$`. The problem is that we would lose some details and in case of an error, the message will be almost meaningless.

Alternatively, if we're going to evolve FlameQL further, I'd also consider using yacc and lex.
