### ISSUE TITLE
Some questions/improvements to the pyroscope/docs/storage-design.md file

### ISSUE THREAD

**Issue by hporro** [grafana/pyroscope#139]
Hi! I read the pyroscope/docs/storage-design.md file and I think is great that you are sharing the way you optimize things!
I thought that you may use some feedback on it, and found some things that I think may also be interesting to read about:

- Why use a segment tree and not another kind of tree data structure (I guess is because the query times, but I think it may be interesting to read about how that impacts your system, and if you tried other data structures).
- In the section "Step 2: Adding tries to store individual symbols more efficiently" you say that you use only 8 bytes to store the trie, but in that count you are not counting the bytes used to store the actual words. I know it is still better to use a trie than just the tree, because in most programs you have a lot of repetition of things in the names of functions, but It would be cool that you talk about it.
- I did't understood totally the gif in the section "Turn reads from O(n) to O(log n)". Maybe you could add a paragraph explaining it further.

**Comment by Rperry2174** [comment]
Thanks for the thoughtful questions @hporro ! Let us take a little time to think about these and give some thoughtful answers :)

**Comment by Rperry2174** [comment]
> Why use a segment tree and not another kind of tree data structure (I guess is because the query times, but I think it may be interesting to read about how that impacts your system, and if you tried other data structures)

Yeah we can go into more depth here, but the three main use cases for segment trees are:
1. Sum all elements in a range
2. Update all elements in a range
3. Find the min or max value of elements in a range

Basically because we are trying to make profiling continuous it helps here to use a segment tree because its generally built for dealing with _ranges_ of units (in this case time) 

> In the section "Step 2: Adding tries to store individual symbols more efficiently" you say that you use only 8 bytes to store the trie, but in that count you are not counting the bytes used to store the actual words. I know it is still better to use a trie than just the tree, because in most programs you have a lot of repetition of things in the names of functions, but It would be cool that you talk about it.

Yeah you're right here we should definitely mention this because it is important. I guess the reason we left it out to begin with is for simplicity. Similar to how even if something is technically O(3n) people will often write O(n) just to simplify since the constant doesn't really matter. In this case, I actually agree though because we don't actually factor in the overhead costs here. 

> I did't understood totally the gif in the section "Turn reads from O(n) to O(log n)". Maybe you could add a paragraph explaining it further.

Yeah I'm thinking of adding some more examples into the gif that shows how many fewer tree merges you have to do when reading with the segment tree. We could even possibly do that actual math here too. So a year worth of data:
- Without segment trees = 3,154,000 join operations. There are that many 10s time blocks in the span of a year aka O(n)
- With segment trees(just doing a simple example):

1 six month tree + 1 three month tree + 1 forty-five day tree + 1 twenty-two day tree + 1 eleven day tree ... 

Basically the number of join operations goes from 3,154,000 down to < 20

 is 3 million+ join operations without segment trees because there are that many 10s time blocks in a year. With the segment trees we could use

**Comment by hporro** [comment]
Thank you!
