### ISSUE TITLE
Deployment for cluster

### ISSUE THREAD

**Issue by evanzhang87** [grafana/pyroscope#1945]
I found that it uses sqlite to save data, so I can just search the local data. When I have a lot of data, how can I get a server with storage from other host? Can I use remote storage?

**Comment by evanzhang87** [comment]
Thanks for your answer, and I took a cursory look at the code again.
My question is mainly about high availability. In my understanding, `Pyroscope Server` is also used as a database in a sense
```mermaid
  graph LR
  agentA -.:4040 .-> Server
  agentB -.:4040 .-> Server
  agentC -.:4040 .-> Server
  UI --> Server
  Server -.local .-> Badgerdb
```
When the service crashes, what will agent do? Does it send data as normal? 
```mermaid
  graph LR
  agentA -.:4040 .-> Nginx
  agentB -.:4040 .-> Nginx
  agentC -.:4040 .-> Nginx
  UI --> Nginx
  Nginx -.-> Server1
  Nginx -.-> Server2
  Nginx -.-> Server3
  Server1 -.remote .-> remote-storage1
  Server2 -.remote .-> remote-storage2
  Server3 -.remote .-> remote-storage3
```
I want to deploy like this. I found that I can send profiles to Phlare via remote-write [doc#](https://pyroscope.io/docs/remote-write/#sending-profiles-to-phlare-via-remote-write).
My question is that when I try to search data from UI, does it return data that combines agentA, B, and C?

**Comment by eh-am** [comment]
Hey!

>My question is mainly about high availability.
The code in this repository (aka "og pyroscope") does not support high availability. Phlare does, though.

>When the service crashes, what will agent do?
Depends on the agent. Some do exponential backoff, some just keep retrying. But don't quote me on that.

> Will pyroscope support this in the future?
My understanding (from this message here https://github.com/grafana/phlare/pull/649#issuecomment-1523454363) is that phlare and "og pyroscope" are being merged into "Grafana Pyroscope".

Based on that, assumine you want high availability, I think you can either
a) Deploy phlare, make your agents write directly to phlare (although the ui is still behind og pyroscope).
b) Deploy pyroscope, make your agents write to pyroscope, then make pyroscope remote write to phlare. It's a bit cheating since you won't have real "high availability", since as you pointed, if pyroscope is down no data will be "remote written" to phlare. 

From your second diagram (and assuming the write path), I believe "Server{1,2,3}" refers to the [Distributor](https://grafana.com/docs/phlare/latest/operators-guide/architecture/components/distributor/), a stateless component, which then responsible for distributing to different ingesters.
