### ISSUE TITLE
Trace and Profile Correlation

### ISSUE THREAD

**Issue by mvkrishna86** [grafana/pyroscope#2356]
#### Is your feature request related to a problem? Please describe.

I would like to correlate the traces and profiling information.

#### Describe the solution you'd like

Need the Pyroscope profile to be correlated with Tempo trace.

#### Additional context

Now I am using grafana for UI, Cortex for Metrics, Tempo for traces and Loki for logs.
I am able to correlate the Logs and Traces which is really useful for the developers and testing teams to debug any issue. Now I have deployed pyroscope for profiling, but not able to correlate with Traces. 

I tried https://github.com/grafana/otel-profiling-java, but dont know how to correlate. more over its updated 6 months ago.

**Comment by kolesnikovae** [comment]
Hello @mvkrishna86, The tracing and profiling integration is something we want to add in the next releases.

I'm wondering how you would like to use it. For example, given a trace ID, which profile would you look into first – the system-wide profile collected within the duration of the trace/span, the whole trace (across multiple services), or a profile for a specific span? Another scenario assumes that one may want to navigate from the profiling data to the trace. For example, to get a trace that contributed most to an unusually expensive function in the flamegraph.

**Comment by mvkrishna86** [comment]
I am trying to explore the functionality given in https://github.com/grafana/otel-profiling-java.

Any correlation would be good to have. TraceID will be spanning across different services. But if we can have the spans correlated which belongs to only one call, that will be great.
Even if we have span to trace, it will be of great help for debugging the performance issues.

**Comment by mvkrishna86** [comment]
Thanks @Rperry2174 for the update.

**Comment by kolesnikovae** [comment]
Hello @mvkrishna86, in order to correlate traces and profiles you need to configure:
 - Our java profiler: https://github.com/grafana/pyroscope-java
 - OTel instrumentation: https://github.com/open-telemetry/opentelemetry-java-instrumentation
 - OTel extension https://github.com/grafana/otel-profiling-java – basically, this component is responsible for the correlation

Please note that the feature is experimental and not yet available in the public Grafana builds, therefore you won't be able to query a span profile in the UI yet. We're working on it, and it will be available very soon!

Please take a look into our demo app – https://github.com/grafana/pyroscope/tree/main/examples/tracing/tempo – this is for Go, but I'm going to add a similar example for a Java app as well

**Comment by mvkrishna86** [comment]
Great, thanks @kolesnikovae for the info. We will try to configure it and will let you know.

**Comment by kolesnikovae** [comment]
@mvkrishna86 I've added an example: https://github.com/grafana/pyroscope/pull/2872, you can test it locally (see [README](https://github.com/grafana/pyroscope/tree/main/examples/tracing/tempo)). Please note that the latest pyroscope version has a bug that breaks the tracing integration for Java: it has been fixed in https://github.com/grafana/pyroscope/pull/2868 but not released yet (the example/demo includes the fix)

**Comment by Rperry2174** [comment]
this now has been added @mvkrishna86 ! https://grafana.com/blog/2024/02/06/combining-tracing-and-profiling-for-enhanced-observability-introducing-span-profiles/

**Comment by mvkrishna86** [comment]
Thanks @Rperry2174

**Comment by YayBurritos** [comment]
Will this be supported by the Pyroscope .net SDK any time soon?
