### ISSUE TITLE
performChecks is not effective when spy is run by non-root user

### ISSUE THREAD

**Issue by AdrK** [grafana/pyroscope#247]
We have a check that is verifying, among others, if system has trace capabilities. If we run the Dockerized example for Ruby (without `--cap-add=SYS_PTRACE`), as it is, we get expected outcome:

```
> podman run -it pyroscope/example_rb:dev       
INFO[2021-06-18T15:40:32.461987] exec/cli.go:76 to disable logging from pyroscope, pass -no-logging argument to pyroscope exec 
Error: if you're running pyroscope in a Docker container, add --cap-add=sys_ptrace. See our Docker Guide for more information: https://pyroscope.io/docs/docker-guide
```

But, if I add this to the Dockerfile:
```
RUN adduser pyroscope
USER pyroscope
```

The check is not performed, and ofc app crashes later:
```
> podman run -it pyroscope/example_rb:dev       
INFO[2021-06-18T15:44:21.148123] exec/cli.go:76 to disable logging from pyroscope, pass -no-logging argument to pyroscope exec 
Error: start session: Couldn't get ruby version: Couldn't determine Ruby version

Caused by:
    0: Operation not permitted (os error 1)
    1: Operation not permitted (os error 1)
```

**Comment by petethepig** [comment]
Hopefully we can get around this limitation soon (see https://github.com/benfred/read-process-memory/pull/9), so we'll be able to drop these checks altogether.

**Comment by anyasabo** [comment]
I was looking into this because it wasn't clear to me why CAP_SYS_PTRACE was still required with the semi-recent docker changes to allow ptrace with the default seccomp profile. It looks like the concern mentioned in the linked PR was addressed by https://github.com/benfred/read-process-memory/pull/4 so I wonder if the capability checks can be removed entirely now as suggested (and perhaps the instructions adjusted to suggest adding sys_ptrace?)
