### ISSUE TITLE
How to understand the length of "self" and "total" in table

### ISSUE THREAD

**Issue by steverao** [grafana/pyroscope#2616]
#### Describe the bug
The length of `self` and `total` in table isn't clear. It seems that the length of each column cannot be understood based on the corresponding numerical value.
![image](https://github.com/grafana/pyroscope/assets/25423978/28d74f8b-94b3-433b-b691-8a8c5c5183bf)

![image](https://github.com/grafana/pyroscope/assets/25423978/2622fc16-7131-4f6b-acd6-56f262d9d579)

**Comment by bryanhuhta** [comment]
Are you viewing this public demo: https://demo.pyroscope.io? We're deprecating that demo in favor of this one: http://play-pyroscope.grafana.org/. In that demo, we have changed the styling of the table view and it no longer includes the colored bars in each cell.

Historically, the bar would indicate the proportion of that row's value compared to the maximum column value. In other words, if the maximum "self" value was 10mb and the function had a "self" value of 5mb, the bar would be half filled. There was a visual bug for the "total" bar, though it doesn't matter anymore since we don't render bars any longer.

**Comment by steverao** [comment]
Ok, I got it. Thank you very much!
