### ISSUE TITLE
question about pyroscope sdk and ebpf api

### ISSUE THREAD

**Issue by DFSOrange** [grafana/pyroscope#2726]
Why does the SDK use the /ingest API while the eBPF injection uses the pushservice API? Is it because of performance considerations? Was there a previous intermediate version of eBPF that used the ingest API for reporting performance?

**Comment by cyriltovena** [comment]
/ingest is the first version of pyroscope, pushservice API is the new API which is based of pprof and recommended as of now. OTEL will most likely be the future and we'll have a 3 API for ingesting :) https://github.com/open-telemetry/oteps/pull/239

We keep the /ingest because it support more other format such jfr from java which is handy.

**Comment by cyriltovena** [comment]
Let me know if you have more questions.
