### ISSUE TITLE
gauge_memberlist_health_score shows zero

### ISSUE THREAD

**Issue by tetsuya28** [grafana/pyroscope#3653]
In Pyroscope v1.9.1, `gauge_memberlist_health_score` shows zero.
Is this fine?

I run Pyroscope with microservices, like ingester, compactor, and distributor.
For ingester, I set replicas to 3, and then I got the metrics is zero.
Zero means fine? or one means fine?

![Image](https://github.com/user-attachments/assets/03c73359-33f0-4fa8-a599-a473bf08c3c1)

**Comment by tetsuya28** [comment]
Also, ingester's memory consumption is differ from each pod.
![Image](https://github.com/user-attachments/assets/d6ba9a34-25f8-4a9a-89bf-d935f2c88987)

**Comment by kolesnikovae** [comment]
Zero `gauge_memberlist_health_score` means that everything is totally find. If you're looking for a metric to track availability of your cluster, you may find the `pyroscope_ring_members` metric more useful.

Regarding the memory consumption pattern: this is expected – the most recently ingested data is kept in memory until it's time to create a new data block (1 hour, by default).

**Comment by kolesnikovae** [comment]
Hi @tetsuya28!

I would recommend keeping the default value if there isn’t a strong reason to do otherwise; honestly, 15 is really too short a time span for Pyroscope. There are quite a few parameters that would need adjustment (e.g., ingestion window, store-gateway discovery delay, compaction delay, etc.), but the thing is that we want to keep the most recent data in memory for performance reasons (this is the classic compute vs. memory trade-off).

Could you please clarify what numbers we’re talking about? I wouldn’t be concerned if this is a couple of GB (2-4) at peak.

**Comment by tetsuya28** [comment]
Our Pyroscope's memory limit is 2GiB, and running with 3 pods for ingester.
Our system has spiky traffic, in that period, ingesters has oom killed.

**Comment by kolesnikovae** [comment]
I would recommend increasing the memory limit (to tolerate spikes) keeping the memory request low – 2GiB should be fine

**Comment by tetsuya28** [comment]
thx
