### ISSUE TITLE
Implement Delete Tags

### ISSUE THREAD

**Issue by eh-am** [grafana/pyroscope#626]
After allowing to delete apps (https://github.com/pyroscope-io/pyroscope/pull/515) the next natural step is to delete tags.

For example, given
```
myapp{pod=autoscale-backend-58f9bc4b7-2nf42}
myapp{pod=autoscale-backend-58f9bc4b7-4wzw6}
myapp{pod=autoscale-backend-58f9bc4b7-7vxk}
```
One would want to delete 
```
myapp{pod=autoscale-backend-58f9bc4b7-2nf42}
```

The CLI API needs to be discussed, `admin app delete tag` or `admin app delete myapp{pod=autoscale-backend-58f9bc4b7-2nf42}` etc.

**Comment by abeaumont** [comment]
I think it may be good to discuss what we understand by tag deletion and what the trade-offs are in the different cases.

Let's begin with some background information. A tag is a pair of `{key, value}` and a time series is composed of an application name (which is just a special tag, but we consider it a separate entity for now) and a set of tags. For example, we may have 4 different time series like these:

1. `app1{key1=val1,key2=val2}`
2. `app1{key1=val1,key2=val2,key3=val3}`
3. `app1{key1=val1,key2=val3}`
4. `app2{key1=val1,key2=val3}`

There are two things to consider in _tag deletion_, let's separate them.

### What tag means

In order to delete tags, we need first to define what a tag is:
- A tag may be considered as the key in the `{key, value}` pair.
  In the above example, all the time series would be _deleted_ by specifying `key1` or `key2`,
  but only the second time series would be _deleted_ by specifying `key3`.
- A tag may be considered as the whole `{key, value}` pair.
  In the above example, all the times series would be _deleted_ by specifying `key1=val1`,
  the first two series would be _deleted_ by specifying `key2=val2`,
  the last two series would be _deleted_ by specifying `key2=val`,
  and only the second series would be _deleted_ by specifying `key3=val3`.

I think both approaches can be useful for different use cases, but the latter seems more useful,
especially when it actually deletes the time series (see next point).

In this latter case, it makes even more sense to [`FlameQL` queries](https://pyroscope.io/docs/flameql/) for deletion,
instead of just a single tag.

### What deletion means

Deletion in this context can mean two different things:
- The time series that contain the tag is deleted. This is the easiest to understand and implement.
- The time series that contain the tag are _aggregated_, that is,
  instead of deleting the series, only the tags are deleted,
  which may result in multiple time series identified by the same tag set.
  In that case, these time series would be aggregated.
  
Let's consider some examples for the latter case, starting from the original example above

If the tag `key1=val` is removed, the resulting series would be:
  
1. `app1{key2=val2}`
2. `app1{key2=val2,key3=val3}`
3. `app1{key2=val3}`
4. `app2{key2=val3}`

In this case, there would be no aggregation.

If the tag `key2=val2` is removed, the resulting series would be:

1. `app1{key1=val1}`
2. `app1{key1=val1,key3=val3}`
3. `app1{key1=val1,key2=val3}`
4. `app2{key1=val1,key2=val3}`

In this case, again, there would be no aggregation.

If the tag `key2` is removed (assuming a tag is just the key in the pair), the resulting series would be:

1. `app1{key1=val1}`
2. `app1{key1=val1,key3=val3}`
3. `app1{key1=val1}`
4. `app2{key1=val1}`

In this case, time series 1 and 3 would be merged into a single time series.

If the tag `key3=val3` is removed, the resulting series would be:

1. `app1{key1=val1,key2=val2}`
2. `app1{key1=val1,key2=val2}`
3. `app1{key1=val1,key2=val3}`
4. `app2{key1=val1,key2=val3}`

In this case, time series 1 and 2 would be merged into a single time series.

As it can be seen in the examples, implementing this latter approach is much more complex, and may yield some unexpected results, so I think the first approach is preferable. In any case, it'd be great to hear some feedback from our users.

**Comment by tuananh2508** [comment]
TBH i didn't think It would be this complicated xD. 

1. 
+ So first, I do think tag should be use with the latter approace which is tag is going to be consider as a FULL `key:value` pair. I think It would be more specific and avoid the case where people got mistake. 
+ In our case, we use Pyroscope on our Kubernetes On-Premises Cluster and add Pyroscope agent to our code (mostly python right now). Then when the Pod got deployed, each pod is going to have some specific tag based on It's Namespace and Hostname (You can clearly see that in the OP, in our case the pod going to have 1 more tag which is the namespace where the pod is currently deployed).
+ So yeah, for this part, I would prefer the second approach because It force user to be more carefully when decided to delete.

2. 
+ For the second part, I would prefer the first way, which is delete the time series which has the tag that was specify by the user. 
+ It would be more simple and easier to implement. And because the first part I choose the 2nd apprach, which force users to list all the tags in the time series they wanted to delete, implement deletion the first way is more rational. 

+ Example for what i mean: 
All the app name and tag right now:
```
myapp{pod=autoscale-backend-58f9bc4b7-2nf42, namespace=staging}
myapp{pod=autoscale-backend-58f9bc4b7-4wzw6, namespace=staging}
myapp{pod=autoscale-backend-58f9bc4b7-7vxk, namespace=production}
```
When user decide to delete they could try
```
admin app delete myapp{pod=autoscale-backend-58f9bc4b7-2nf42, namespace=staging}
-> Delete the time series
```

Case where the user specify "not enough" tags
```
admin app delete myapp{pod=autoscale-backend-58f9bc4b7-2nf42}
-> Not found or smt here
```

**Comment by Rperry2174** [comment]
Adding a profile of what happens on the server when deleting apps:
https://github.com/pyroscope-io/flamegraph.com/issues/231#issuecomment-1044192150
