### ISSUE TITLE
feat: grafana panel plugin supports two theme mod

### ISSUE THREAD

**Issue by linthan** [grafana/pyroscope#664]
the  pyroscope panel plugin  just looks good in grafana dark mod. it looks weird  in light mod.

**Comment by linthan** [comment]
the reason is the background and the button color is black.  grafana inherit  it.
![image](https://user-images.githubusercontent.com/13914829/147715868-66fe5cc0-2d59-43d6-9127-e4d1428c68e3.png)

**Comment by eh-am** [comment]
That's a great point, there's nothing **requiring** the background to be dark, so it should work!

The only thing is that we are importing the whole `styles.scss`, which as you pointed, comes with the body styling stuff. IIRC we do that due to other required styling.

I'm thinking here to simply break down the styles into:
* a `shared.scss` file (which hopefully goes away in the future, once we move more and more to css modules)
* a `panel.scss`, which has panel specific styles (maybe it's not even required) AND imports `shared.scss`
* a `webapp.scss`, which has webapp specific styles AND imports `shared.scss`
